server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://cloud-live-user # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/** # 这里是以请求路径作为判断规则
          filters:
            - StripPrefix=1
        - id: im
          uri: lb://cloud-live-im
          predicates:
            - Path=/im/**
          filters:
            - StripPrefix=1
        - id: living
          uri: lb://cloud-live-living
          predicates:
            - Path=/living/**
          filters:
            - StripPrefix=1
        - id: router
          uri: lb://cloud-live-router
          predicates:
            - Path=/router/**
          filters:
            - StripPrefix=1
        - id: shop
          uri: lb://cloud-live-shop
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1
        - id: pay
          uri: lb://cloud-live-pay
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1
