DROP TABLE IF EXISTS t_sms;
CREATE TABLE t_sms  (
      id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
      code int UNSIGNED NULL DEFAULT 0 COMMENT '验证码',
      phone varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '手机号',
      sendTime datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
      updateTime datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 15 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;